### ISSUE TITLE
Failed to run the examples in release-0.4.0 branch

### ISSUE THREAD

**Issue by etxian** [GoogleCloudPlatform/open-match#192]
Hi, I'm trying to follow the README.md and get everything in open-match working. The open-match server itself is working fine. However I can't get the example running properly. Several pods in install-example-chart steps failed to startup. Here are the logs for these pods.

om-functions error log:
```
MMF request inserted at  
Looking for profile in key 
Placing results in MatchObjectID 
=========Profile
{}
=========Pools
pool.String() = 
=========Rosters
rosters.String() = 
Adding 0 players to ignorelist
Unable to add proposed players to the ignorelist
DECR concurrentMMFs
panic: ERR wrong number of arguments for 'zadd' command
 goroutine 1 [running]:
main.main()
    /go/src/github.com/GoogleCloudPlatform/open-match/examples/functions/golang/manual-simple/main.go:307 +0x2949
```

om-evaluator log (not sure it's error or not, but the pod is failing):
```
time="2019-04-10T08:14:07Z" level=info msg="Connected to Redis" app=openmatch component=redishelpers
MMFEvalStub: 2019/04/10 08:14:07 Initializing example MMF proposal evaluator
MMFEvalStub: 2019/04/10 08:14:07 SCARD proposalq
MMFEvalStub: 2019/04/10 08:14:07 SPOP proposalq 0
proposals = []
overloadedPlayers
{
}
overloadePlayerList
[
]
overloadedMatchList
[
]
approvedMatchList
[
]
overloaded = []
len(overloaded) = 0
MMFEval: 2019/04/10 08:14:07 0 Finished in 0.001261694 seconds.
```

testprofilev job error log:
```
Traceback (most recent call last):
  File "./harness.py", line 42, in <module>
    profile_pb = mmlogic_api.GetProfile(mmlogic.MatchObject(id=os.environ["MMF_PROFILE_ID"]))
  File "/usr/local/lib/python3.5/site-packages/grpc/_channel.py", line 532, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/local/lib/python3.5/site-packages/grpc/_channel.py", line 466, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
    status = StatusCode.UNAVAILABLE
    details = "Connect Failed"
    debug_error_string = "{"created":"@1554883817.700357266","description":"Failed to create subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":2636,"referenced_errors":[{"created":"@1554883817.700353169","description":"Pick Cancelled","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":241,"referenced_errors":[{"created":"@1554883817.700174301","description":"Connect Failed","file":"src/core/ext/filters/client_channel/subchannel.cc","file_line":663,"grpc_status":14,"referenced_errors":[{"created":"@1554883817.699862622","description":"Failed to connect to remote host: OS Error","errno":111,"file":"src/core/lib/iomgr/tcp_client_posix.cc","file_line":202,"os_error":"Connection refused","syscall":"connect","target_address":"ipv4:10.111.85.177:50503"}]}]}]}"
```

I'm running the example on MacOS minikube. Here are the commands I used:
```
make install-toolchain
make all-protos
make all
make create-mini-cluster
make push-helm
make push-images -j4
make install-chart
make install-example-chart
```

Do these error log matter anyway? Or is there anything I did wrong? Thanks for your time, any help will be appreciated.

**Comment by jeremyje** [comment]
The first bug has been fixed yesterday at head. Testprofilev job looks like the om-mmlogicapi was not running when this started. It could be a timing issue that goes away after reattempt.
